[package]
name = "send-vrc-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
axum = "0.4.4"
tokio = { version = "1.15.0", features = ["full"] }
serde = { version = "1.0.135", features = ["derive"] }
clipboard-win = "4.4.0"
windows = { version = "0.30.0", features = ["alloc", "Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
